kind: LimitRange
apiVersion: v1
metadata:
   name: nginx-limitrange
   namespace: nginx
spec:
  limits:
    - type: Container
      default: 
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
      max: 
        cpu: "1"
        memory: "1Gi"
      min: 
        cpu: "100m"
        memory: "128Mi"
